### ISSUE TITLE
Custom Id Identity - Cordova Plugin Blink ID

### ISSUE THREAD

**Issue by SergiioXs** [BlinkOCR/blinkocr-android#18]
Hi, I am using ionic 1, I need to read an area of the Mexican credential "CURP", but I have not been able to find a way to do it, nor in what file can I integrate this functionality. I do not know if there is a function that allows me to define the area to be read?

**Comment by DoDoENT** [comment]
Hi @SergiioXs. In order to achieve that, you will need to use the [Templating API](https://github.com/blinkinput/blinkinput-android#detectorRecognizer_templating). 

A detailed description about the templating API is given [here](https://github.com/BlinkID/blinkid-android/blob/master/templatingAPI/templatingAPI.md) and full examples are available as part of our [BlinkID SDK](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkIDSample-BlinkIDSample/src/main/java/com/microblink/util/templating).

BlinkInput SDK does not have support for MRTD-based templating, but does support templating based on detection of card-like documents.

Both BlinkID and BlinkInput support templating API only when using native iOS or Android integration. If you need that functionality in cordova/phonegap app, then you should fork our [official BlinkID phonegap plugin source code](https://github.com/blinkid/blinkid-phonegap) and modify it so that bridge towards java/objective C performs the templating API-based integration suited for your needs.

BlinkInput SDK does not have an official phonegap plugin but you can use BlinkID wrapper's source code as starting point to create one.

**Comment by DoDoENT** [comment]
Hi @SergiioXs, you can achieve that by using the [Templating API](https://github.com/blinkinput/blinkinput-android#detectorRecognizer_templating).

For more information about the Templating API, see this [detailed description](https://github.com/BlinkID/blinkid-android/blob/master/templatingAPI/templatingAPI.md) and also [these code examples](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkIDSample-BlinkIDSample/src/main/java/com/microblink/util/templating).

The Templating API is available only for iOS and Android SDKs, not for Cordova SDK. However, you can fork our [BlinkID cordova plugin source code](https://github.com/BlinkID/blinkid-phonegap) and use it as a basis for creating your own wrapper around native code that uses the Templating API to add support for your documents.

Note that BlinkInput does not have an official Cordova plugin, but you can use BlinkID plugin's source code to create one that suits your needs.

**Comment by SergiioXs** [comment]
Thanks you,  can you send us, a example of code, using native Android, where only I can read one line? With a easy template, whit that, I will understand what is the structure.

Thanks.

**Comment by DoDoENT** [comment]
Hi @SergiioXs!

[Here](https://github.com/BlinkID/blinkid-android/blob/master/templatingAPI/templatingAPI.md#-templating-api-for-generic-documents) is description of [example for arbitrary templates](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkIDSample-BlinkIDSample/src/main/java/com/microblink/util/templating/CroatianIDFrontSide.java).

You can use that example for scanning only one line of text from your document.

**Comment by culoi** [comment]
Closing issue.

Please reopen if you have additional question.

Regards
