### ISSUE TITLE
BicParserSettings to go along with IbanParserSettings

### ISSUE THREAD

**Issue by JPierron** [BlinkOCR/blinkocr-android#7]
Hi,

Are you planning on implementing Bank Identifier Code recognition to go along with Iban recognition ?

These would go quite well together for, say, fetching SEPA information via OCR.

I've tried with a RegexParserSettings, but formattings for BIC number are too disparate so that a regex could do the job.
http://www.office-agglo-larochelle.fr/uploaded/fichier/rib-caisse-epargne_1397138617.jpg
http://www.le-geant-de-la-fete.com/media//RIB.JPG

I've also considered the possibility of extending OcrParserSettings, but that seems like to much work if you're going to release one some time soon.

Thanks.
Regards.

**Comment by i1E** [comment]
Hi @JPierron,

we are planning to implement BIC parser in the next few weeks and it will be available in the SDK. Until then you can continue using the regex parser. To get better results from the regex parser, you can define the [BlinkOCREngineOptions](https://blinkocr.github.io/blinkocr-android/com/microblink/recognizers/blinkocr/engine/BlinkOCREngineOptions.html) for your use case and [set them](https://blinkocr.github.io/blinkocr-android/com/microblink/recognizers/blinkocr/parser/regex/RegexParserSettings.html#setOcrEngineOptions-com.microblink.recognizers.blinkocr.engine.BlinkOCREngineOptions-) on **RegexParserSettings**. It is important to define whitelist of characters for the OCR engine by using the methods from **BlinkOCREngineOptions**. Please take a look at [this example](https://github.com/BlinkOCR/blinkocr-android/blob/master/BlinkOCRDemo/BlinkOCRSegmentDemo/src/main/java/com/microblink/ocr/MainActivity.java#L85) for parsing the VIN (Vehicle Identification Number) numbers.

 Reading of BIC numbers in boxes, like the one from the first link, will not be supported because boxes are confusing the OCR engine and it interprets them as valid characters.

Regarding to extending the _OcrParserSettings_, this class is not intended for users of the SDK to extend it, because all parsers are implemented in the native code and Android NDK is used to call the native functions. _OcrParserSettings_ and it subclasses are used to define which parser will be used and to tweak settings for specific parser.

Best regards

**Comment by JPierron** [comment]
Hi @i1E,

Thank you for this quick answer.

I'm glad to hear you're planning on releasing this feature.

Regarding the non-support of BIC numbers in boxes, are you talking about the RegexParserSettings/BlinkOCREngineOptions combo solution, or your coming BIC parser implementation ? Both ?

Thanks again.

**Comment by i1E** [comment]
Hi @JPierron,

It is not possible to parse BIC numbers in boxes with _RegexParser_ and they won't be supported with BIC parser that will be provided because boxes can be recognised as valid BIC characters and it is very hard to ignore them during extraction.
